version: '3.8'
services:

  service-db:
    container_name: data_base
    image: "postgres:15"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: "/data/postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

    ports:
      - "5433:5432"
