version: '3.8'
services:

  service-db:
    image: radomskaya/db_kinorate
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata: